print ("Hello! I am here for the interview! I will ask you each your birthdays. \nFirst,")
mybirthday = input("Avanthika, when is your birthday?")
print("I can't believe your birthday is on the" ,mybirthday)
birthday = input("Pavneet, when is your birthday?")
print("I can't believe your birthday is on the" ,birthday)
yourbirthday = input("Now, Emaan, when is your birthday?")
print("I can't believe your birthday is on the" ,yourbirthday)
birthdays = input("Now, Isabella, when is your birthday?")
print("I can't believe your birthday is on the" ,birthdays)
yaybirthday = input("Lastly, Mokshitha when is your birthday?")
print("I can't believe your birthday is on the" ,yaybirthday)
print("That is the end! Goodbye! Thank you for letting me do the interview!👋😊🥰")